# build
name: build
on:
  push:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/build.yml"
      - "!*.md"
      - "!.gitignore"
      - "!.gitmodules"
jobs:
  build-wheel-win:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2022
            cuda: "11.8.0"
            visual_studio: "Visual Studio 17 2022"
          - os: windows-2022
            cuda: "11.7.0"
            visual_studio: "Visual Studio 17 2022"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install CUDA
        env:
          cuda: ${{ matrix.cuda }}
          visual_studio: ${{ matrix.visual_studio }}
        shell: powershell
        run: .\scripts\install_cuda_windows.ps1

      - name: nvcc check
        shell: powershell
        run: |
          nvcc -V
          ls $env:CUDA_PATH
          ls $env:CUDA_PATH\bin
          ls $env:CUDA_PATH\include

      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        shell: powershell
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        shell: bash
        run: |
          rm -rf ./wheelhouse
          python -m cibuildwheel --output-dir wheelhouse

      - name: Change names
        env: 
          CUDA_VERSION: ${{matrix.cuda}}
        run: python ./scripts/rename_wheels.py

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
#------------------------------------------#
  build-wheel-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            cuda: "11.8"
          - os: ubuntu-latest
            cuda: "11.7"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        shell: bash
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: sameli/manylinux2014_x86_64_cuda_${{matrix.cuda}}
        run: |
          rm -rf ./wheelhouse
          python -m cibuildwheel --output-dir wheelhouse

      - name: Change names
        env: 
          CUDA_VERSION: ${{matrix.cuda}}
        run: python ./scripts/rename_wheels.py

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl


