name: upload
on:
  workflow_run:
    workflows: [build]
    types: [completed]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Make temp dir
        run: mkdir -pv wheels
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: ./wheels
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./wheels/
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Build failed!!!!'
