# build
name: win_build
on:
  push:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/win_build.yml"
      - "!*.md"
      - "!.gitignore"
      - "!.gitmodules"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          - os: windows-2022
            cuda: "12.0.0"
            visual_studio: "Visual Studio 17 2022"
          - os: windows-2022
            cuda: "11.8.0"
            visual_studio: "Visual Studio 17 2022"
          - os: windows-2022
            cuda: "11.7.0"
            visual_studio: "Visual Studio 17 2022"
    steps:
      - uses: actions/checkout@v3

      - name: Install CUDA
        env: 
          cuda: ${{ matrix.cuda }}
          visual_studio: ${{ matrix.visual_studio }}
        shell: powershell
        run: .\scripts\install_cuda_windows.ps1
      
      - name: nvcc check
        shell: powershell
        run: |
          nvcc -V
          ls $env:CUDA_PATH
          ls $env:CUDA_PATH\bin
          ls $env:CUDA_PATH\include
      
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        shell: powershell
        run: python -m pip install cibuildwheel==2.16.2
      
      - name: Write version to file
        shell: powershell
        env:
          CUDA_VERSION: ${{ matrix.cuda }}
        run: python ./scripts/make_version.py
      
      - name: Build wheels
        shell: powershell
        run: python -m cibuildwheel --output-dir wheelhouse
      
      